//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINTERS_MODELS
    {
        public int IDDETMODEL { get; set; }
        public string MODEL { get; set; }
        public string LINE { get; set; }
        public string PRINTER { get; set; }
        public string IPPRINTER { get; set; }
        public int IDLINE { get; set; }
        public int IDPRINTER { get; set; }
    }
}
