//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class se_model_tbls_t
    {
        public int se_id { get; set; }
        public string se_ict { get; set; }
        public string se_fct { get; set; }
        public string se_cover { get; set; }
        public string se_pack { get; set; }
        public string se_gb { get; set; }
    }
}
