//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_tblModels_cfg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_tblModels_cfg()
        {
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
        }
    
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public string se_tbl_ict { get; set; }
        public string se_tbl_fct { get; set; }
        public string se_tbl_cover { get; set; }
        public string se_tbl_pack { get; set; }
        public string se_tbl_gb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
        public virtual siixsem_models_t siixsem_models_t { get; set; }
    }
}
