//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_labels_path
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_labels_path()
        {
            this.siixsem_models_lbl_cfg_td = new HashSet<siixsem_models_lbl_cfg_td>();
            this.siixsem_models_lbl_cfg_td1 = new HashSet<siixsem_models_lbl_cfg_td>();
            this.siixsem_models_lbl_cfg_td2 = new HashSet<siixsem_models_lbl_cfg_td>();
            this.siixsem_models_lbl_cfg_td3 = new HashSet<siixsem_models_lbl_cfg_td>();
            this.siixsem_models_lbl_cfg_td4 = new HashSet<siixsem_models_lbl_cfg_td>();
        }
    
        public int se_id { get; set; }
        public string se_description { get; set; }
        public string se_path { get; set; }
        public int se_id_port { get; set; }
        public int se_id_server { get; set; }
    
        public virtual siixsem_ports_t siixsem_ports_t { get; set; }
        public virtual sixsem_servers_t sixsem_servers_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_lbl_cfg_td> siixsem_models_lbl_cfg_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_lbl_cfg_td> siixsem_models_lbl_cfg_td1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_lbl_cfg_td> siixsem_models_lbl_cfg_td2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_lbl_cfg_td> siixsem_models_lbl_cfg_td3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_lbl_cfg_td> siixsem_models_lbl_cfg_td4 { get; set; }
    }
}
