//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_model_cfg_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_model_cfg_t()
        {
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
        }
    
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public string se_serial_length { get; set; }
        public Nullable<int> id_rev { get; set; }
        public int id_rules { get; set; }
    
        public virtual siixsem_models_t siixsem_models_t { get; set; }
        public virtual siixsem_reviews_t siixsem_reviews_t { get; set; }
        public virtual siixsem_rules_t siixsem_rules_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
    }
}
