//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_model_cover_cfg_td
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_model_cover_cfg_td()
        {
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
        }
    
        public int se_id { get; set; }
        public int se_id_model_pck_cfg { get; set; }
        public int se_id_trac { get; set; }
        public string se_cover_ident { get; set; }
        public string se_serial_lenght { get; set; }
        public int se_id_label { get; set; }
        public int se_id_tbl { get; set; }
        public int se_is_laser_mark { get; set; }
        public string se_cover_id_model { get; set; }
        public string se_prg_ver { get; set; }
        public string se_plant_code { get; set; }
        public string se_ko_part_num { get; set; }
        public string se_line_name { get; set; }
        public string se_cov_id_11 { get; set; }
        public int se_id_format_qr { get; set; }
        public int se_id_format_serial { get; set; }
        public int se_pos_year { get; set; }
        public int se_pos_day { get; set; }
    
        public virtual siixsem_cover_formats_t siixsem_cover_formats_t { get; set; }
        public virtual siixsem_cover_formats_t siixsem_cover_formats_t1 { get; set; }
        public virtual siixsem_lblMods_td siixsem_lblMods_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
    }
}
