//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_920B_M_SMART_LDM_cov
    {
        public int se_id { get; set; }
        public string se_serial_pcb { get; set; }
        public string se_serial_cover { get; set; }
        public string se_status { get; set; }
        public System.DateTime se_create_date { get; set; }
        public int se_id_line { get; set; }
        public Nullable<System.DateTime> se_delete_date { get; set; }
        public int se_id_user { get; set; }
        public string se_serial11 { get; set; }
        public int se_consecutive { get; set; }
    }
}
