//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_inf_td
    {
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public int se_id_side { get; set; }
        public string se_description { get; set; }
        public string se_customer_no { get; set; }
        public string se_traceability_no { get; set; }
        public string se_intern_part_no { get; set; }
        public int se_serial_length { get; set; }
        public int se_std_pack { get; set; }
        public int se_id_review { get; set; }
        public int se_id_tbl { get; set; }
        public int se_id_lbl_cfg { get; set; }
        public System.DateTime se_creation_date { get; set; }
        public Nullable<System.DateTime> se_update_date { get; set; }
        public int se_active { get; set; }
        public int se_type { get; set; }
        public Nullable<int> se_serials_to_read { get; set; }
    
        public virtual siixsem_models_lbl_cfg_td siixsem_models_lbl_cfg_td { get; set; }
        public virtual siixsem_models_tbl_td siixsem_models_tbl_td { get; set; }
    }
}
