//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_model_pck_cfg_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_model_pck_cfg_t()
        {
            this.siixsem_kit_cfg_dt = new HashSet<siixsem_kit_cfg_dt>();
            this.siixsem_model_printers_dt = new HashSet<siixsem_model_printers_dt>();
        }
    
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public int se_id_side { get; set; }
        public int se_is_kit { get; set; }
        public Nullable<int> se_id_model_cfg { get; set; }
        public int se_has_cover { get; set; }
        public Nullable<int> se_id_cover { get; set; }
        public int se_id_tables { get; set; }
        public int se_id_cust_no { get; set; }
        public int se_id_internal_no { get; set; }
        public Nullable<int> se_id_trac_no { get; set; }
        public int se_id_label { get; set; }
        public int se_box_qty { get; set; }
        public string se_kanban { get; set; }
        public int se_id_line { get; set; }
        public bool se_validate_bin { get; set; }
        public string se_cust_name { get; set; }
        public bool se_mp_enable { get; set; }
    
        public virtual siixsem_customer_no_t siixsem_customer_no_t { get; set; }
        public virtual siixsem_internal_no_t siixsem_internal_no_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_kit_cfg_dt> siixsem_kit_cfg_dt { get; set; }
        public virtual siixsem_lblMods_td siixsem_lblMods_td { get; set; }
        public virtual siixsem_lines_t siixsem_lines_t { get; set; }
        public virtual siixsem_model_cfg_t siixsem_model_cfg_t { get; set; }
        public virtual siixsem_model_cover_cfg_td siixsem_model_cover_cfg_td { get; set; }
        public virtual siixsem_models_t siixsem_models_t { get; set; }
        public virtual siixsem_models_t siixsem_models_t1 { get; set; }
        public virtual siixsem_sides_t siixsem_sides_t { get; set; }
        public virtual siixsem_tblModels_cfg siixsem_tblModels_cfg { get; set; }
        public virtual siixsem_traceabilty_no_t siixsem_traceabilty_no_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_printers_dt> siixsem_model_printers_dt { get; set; }
    }
}
