//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_3W0A_D_pck
    {
        public int se_id { get; set; }
        public string se_serial { get; set; }
        public int se_box_no { get; set; }
        public int se_julian_date { get; set; }
        public string se_status { get; set; }
        public System.DateTime se_create_date { get; set; }
        public int se_id_prod_line { get; set; }
        public Nullable<int> se_box_id { get; set; }
        public Nullable<System.DateTime> se_delete_date { get; set; }
        public string se_dj_group { get; set; }
    }
}
