//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_model_printers_dt
    {
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public int se_id_line { get; set; }
        public string se_computer_name { get; set; }
    
        public virtual siixsem_lines_t siixsem_lines_t { get; set; }
        public virtual siixsem_model_pck_cfg_t siixsem_model_pck_cfg_t { get; set; }
    }
}
