//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_010B_BUL_PCA_F_gb
    {
        public int se_id { get; set; }
        public int se_julian_date { get; set; }
        public string se_serial_box { get; set; }
        public System.DateTime se_date_created_box { get; set; }
        public System.DateTime se_date_created_label { get; set; }
        public int se_id_line { get; set; }
        public int se_id_user { get; set; }
        public int se_id_model { get; set; }
        public int se_box_n { get; set; }
        public int se_box_qty { get; set; }
    }
}
