//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_current_box_model
    {
        public int se_id { get; set; }
        public string se_model { get; set; }
        public int se_curr_box { get; set; }
        public System.DateTime se_date_update { get; set; }
        public int se_julian_date { get; set; }
        public Nullable<System.DateTime> se_created_date { get; set; }
    }
}
