//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_lbl_cfg_td
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_lbl_cfg_td()
        {
            this.siixsem_models_inf_td = new HashSet<siixsem_models_inf_td>();
        }
    
        public int se_id { get; set; }
        public int se_id_print_type { get; set; }
        public int se_labels_qty { get; set; }
        public string se_lbl_descripction { get; set; }
        public int se_id_path_full_lbl { get; set; }
        public int se_id_path_partial_lbl { get; set; }
        public int se_id_path_eng_change_full_lbl { get; set; }
        public int se_id_path_eng_change_part_lbl { get; set; }
        public int se_id_path_cover_lbl { get; set; }
    
        public virtual siixsem_labels_path siixsem_labels_path { get; set; }
        public virtual siixsem_labels_path siixsem_labels_path1 { get; set; }
        public virtual siixsem_labels_path siixsem_labels_path2 { get; set; }
        public virtual siixsem_labels_path siixsem_labels_path3 { get; set; }
        public virtual siixsem_labels_path siixsem_labels_path4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_inf_td> siixsem_models_inf_td { get; set; }
    }
}
