//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_pending_change
    {
        public int ID { get; set; }
        public string Model_name { get; set; }
        public string Internal_num_uni { get; set; }
        public string Internal_num_lh { get; set; }
        public string Internal_num_rh { get; set; }
        public string Customer_num_uni { get; set; }
        public string Customer_num_lh { get; set; }
        public string Customer_num_rh { get; set; }
        public string Tazability_num_uni { get; set; }
        public string Tazability_num_lh { get; set; }
        public string Tazability_num_rh { get; set; }
        public string Kanban_uni { get; set; }
        public string Kanban_lh { get; set; }
        public string Kanban_rh { get; set; }
        public int Digits { get; set; }
        public int Standar_Pack { get; set; }
        public string Flux_1 { get; set; }
        public Nullable<int> Flux_1_Pos_Start { get; set; }
        public Nullable<int> Flux_1_Pos_End { get; set; }
        public Nullable<int> Flux_1_Val { get; set; }
        public string Flux_2 { get; set; }
        public Nullable<int> Flux_2_Pos_Start { get; set; }
        public Nullable<int> Flux_2_Pos_End { get; set; }
        public Nullable<int> Flux_2_Val { get; set; }
        public string Voltage_1 { get; set; }
        public Nullable<int> Volt_1_Pos_Start { get; set; }
        public Nullable<int> Volt_1_Pos_End { get; set; }
        public Nullable<int> Voltage_1_Val { get; set; }
        public string Voltage_2 { get; set; }
        public Nullable<int> Volt_2_Pos_Start { get; set; }
        public Nullable<int> Volt_2_Pos_End { get; set; }
        public Nullable<int> Voltage_2_Val { get; set; }
        public string Color_1 { get; set; }
        public Nullable<int> Color_1_Pos_Start { get; set; }
        public Nullable<int> Color_1_Pos_End { get; set; }
        public Nullable<int> Color_1_Val { get; set; }
        public string Color_2 { get; set; }
        public Nullable<int> Color_2_Pos_Start { get; set; }
        public Nullable<int> Color_2_Pos_End { get; set; }
        public Nullable<int> Color_2_Val { get; set; }
        public string Label_type { get; set; }
        public string Request { get; set; }
        public Nullable<int> Gapfiler_Validation { get; set; }
        public Nullable<int> FlashProgrammer_validation { get; set; }
        public Nullable<int> ICT_Validation { get; set; }
        public Nullable<int> FCT_Midle_Validation { get; set; }
        public Nullable<int> FCT_Final_Validation { get; set; }
        public Nullable<int> FCT_Time_Validation { get; set; }
        public Nullable<int> DJ_Criterio { get; set; }
        public Nullable<int> DJ_Validation { get; set; }
        public string DJ_Coments { get; set; }
        public Nullable<int> Dj_number { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime Fin_Date { get; set; }
        public System.DateTime Modification_Date { get; set; }
        public string Usuario { get; set; }
    }
}
