//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_tbl_td
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_tbl_td()
        {
            this.siixsem_models_inf_td = new HashSet<siixsem_models_inf_td>();
        }
    
        public int se_id { get; set; }
        public string se_tbl_fct { get; set; }
        public string se_tbl_pack { get; set; }
        public string se_tbl_cover { get; set; }
        public string se_tbl_gb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_inf_td> siixsem_models_inf_td { get; set; }
    }
}
