//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_lblMods_td
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_lblMods_td()
        {
            this.siixsem_model_cover_cfg_td = new HashSet<siixsem_model_cover_cfg_td>();
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
        }
    
        public int se_id { get; set; }
        public int se_id_model { get; set; }
        public int se_id_label { get; set; }
        public int se_id_side { get; set; }
        public int se_id_lbl_type { get; set; }
    
        public virtual siixsem_labels_t siixsem_labels_t { get; set; }
        public virtual siixsem_lbl_type_t siixsem_lbl_type_t { get; set; }
        public virtual siixsem_models_t siixsem_models_t { get; set; }
        public virtual siixsem_sides_t siixsem_sides_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_cover_cfg_td> siixsem_model_cover_cfg_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
    }
}
