//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_colors_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_colors_t()
        {
            this.siixsem_bines_2_dt = new HashSet<siixsem_bines_2_dt>();
            this.siixsem_bines_dt = new HashSet<siixsem_bines_dt>();
        }
    
        public int se_id { get; set; }
        public string se_name { get; set; }
        public string se_lbl { get; set; }
        public string se_lbl_pck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_bines_2_dt> siixsem_bines_2_dt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_bines_dt> siixsem_bines_dt { get; set; }
    }
}
