//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_cover_formats_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_cover_formats_t()
        {
            this.siixsem_model_cover_cfg_td = new HashSet<siixsem_model_cover_cfg_td>();
            this.siixsem_model_cover_cfg_td1 = new HashSet<siixsem_model_cover_cfg_td>();
        }
    
        public int se_id { get; set; }
        public string se_description { get; set; }
        public string se_detailed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_cover_cfg_td> siixsem_model_cover_cfg_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_cover_cfg_td> siixsem_model_cover_cfg_td1 { get; set; }
    }
}
