//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_sides_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_sides_t()
        {
            this.siixsem_customer_no_t = new HashSet<siixsem_customer_no_t>();
            this.siixsem_internal_no_t = new HashSet<siixsem_internal_no_t>();
            this.siixsem_lblMods_td = new HashSet<siixsem_lblMods_td>();
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
            this.siixsem_traceabilty_no_t = new HashSet<siixsem_traceabilty_no_t>();
        }
    
        public int se_id { get; set; }
        public string se_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_customer_no_t> siixsem_customer_no_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_internal_no_t> siixsem_internal_no_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_lblMods_td> siixsem_lblMods_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_traceabilty_no_t> siixsem_traceabilty_no_t { get; set; }
    }
}
