//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_t()
        {
            this.siixsem_bines_2_dt = new HashSet<siixsem_bines_2_dt>();
            this.siixsem_bines_dt = new HashSet<siixsem_bines_dt>();
            this.siixsem_customer_no_t = new HashSet<siixsem_customer_no_t>();
            this.siixsem_kit_cfg_dt = new HashSet<siixsem_kit_cfg_dt>();
            this.siixsem_lblMods_td = new HashSet<siixsem_lblMods_td>();
            this.siixsem_model_cfg_t = new HashSet<siixsem_model_cfg_t>();
            this.siixsem_model_pck_cfg_t = new HashSet<siixsem_model_pck_cfg_t>();
            this.siixsem_model_pck_cfg_t1 = new HashSet<siixsem_model_pck_cfg_t>();
            this.siixsem_models_validation_td = new HashSet<siixsem_models_validation_td>();
            this.siixsem_rules_t = new HashSet<siixsem_rules_t>();
            this.siixsem_tblModels_cfg = new HashSet<siixsem_tblModels_cfg>();
        }
    
        public int se_id { get; set; }
        public string se_description { get; set; }
        public int se_id_family { get; set; }
        public int se_status { get; set; }
        public bool se_blocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_bines_2_dt> siixsem_bines_2_dt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_bines_dt> siixsem_bines_dt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_customer_no_t> siixsem_customer_no_t { get; set; }
        public virtual siixsem_family_t siixsem_family_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_kit_cfg_dt> siixsem_kit_cfg_dt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_lblMods_td> siixsem_lblMods_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_cfg_t> siixsem_model_cfg_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_model_pck_cfg_t> siixsem_model_pck_cfg_t1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_models_validation_td> siixsem_models_validation_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_rules_t> siixsem_rules_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_tblModels_cfg> siixsem_tblModels_cfg { get; set; }
    }
}
