//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upacking_bajas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_casualty_log
    {
        public int se_id { get; set; }
        public Nullable<int> se_id_user { get; set; }
        public Nullable<int> se_id_model { get; set; }
        public string se_type { get; set; }
        public string se_comments { get; set; }
    }
}
